services:
  discord-bot:
    image: llmcord-discord-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/usr/src/app/config.yaml:ro
      - ./data:/usr/src/app/data
    environment:
      - TZ=Asia/Macau
